In [1]:
import json
import pandas as pd

In [2]:
file_name = "CORD-19-research-challenge/metadata.csv"
df = pd.read_csv(file_name)
df.head()

/var/folders/m8/6fld5z8d42q7cprjnz1lpmlr0000gn/T/ipykernel_8112/3624613813.py:2: DtypeWarning: Columns (1,4,5,6,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

,cord_uid,sha,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,mag_id,who_covidence_id,arxiv_id,pdf_json_files,pmc_json_files,url,s2_id
0,ug7v899j,d1aafb70c066a2068b02786f8929fd9c900897fb,PMC,Clinical features of culture-proven Mycoplasma...,10.1186/1471-2334-1-6,PMC35282,11472636,no-cc,OBJECTIVE: This retrospective chart review des...,2001-07-04,"Madani, Tariq A; Al-Ghamdi, Aisha A",BMC Infect Dis,NaN,NaN,NaN,document_parses/pdf_json/d1aafb70c066a2068b027...,document_parses/pmc_json/PMC35282.xml.json,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3...,NaN
1,02tnwd4m,6b0567729c2143a66d737eb0a2f63f2dce2e5a7d,PMC,Nitric oxide: a pro-inflammatory mediator in l...,10.1186/rr14,PMC59543,11667967,no-cc,Inflammatory diseases of the respiratory tract...,2000-08-15,"Vliet, Albert van der; Eiserich, Jason P; Cros...",Respir Res,NaN,NaN,NaN,document_parses/pdf_json/6b0567729c2143a66d737...,document_parses/pmc_json/PMC59543.xml.json,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...,NaN
2,ejv2xln0,06ced00a5fc04215949aa72528f2eeaae1d58927,PMC,Surfactant protein-D and pulmonary host defense,10.1186/rr19,PMC59549,11667972,no-cc,Surfactant protein-D (SP-D) participates in th...,2000-08-25,"Crouch, Erika C",Respir Res,NaN,NaN,NaN,document_parses/pdf_json/06ced00a5fc04215949aa...,document_parses/pmc_json/PMC59549.xml.json,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...,NaN
3,2b73a28n,348055649b6b8cf2b9a376498df9bf41f7123605,PMC,Role of endothelin-1 in lung disease,10.1186/rr44,PMC59574,11686871,no-cc,Endothelin-1 (ET-1) is a 21 amino acid peptide...,2001-02-22,"Fagan, Karen A; McMurtry, Ivan F; Rodman, David M",Respir Res,NaN,NaN,NaN,document_parses/pdf_json/348055649b6b8cf2b9a37...,document_parses/pmc_json/PMC59574.xml.json,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...,NaN
4,9785vg6d,5f48792a5fa08bed9f56016f4981ae2ca6031b32,PMC,Gene expression in epithelial cells in respons...,10.1186/rr61,PMC59580,11686888,no-cc,Respiratory syncytial virus (RSV) and pneumoni...,2001-05-11,"Domachowske, Joseph B; Bonville, Cynthia A; Ro...",Respir Res,NaN,NaN,NaN,document_parses/pdf_json/5f48792a5fa08bed9f560...,document_parses/pmc_json/PMC59580.xml.json,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5...,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056660 entries, 0 to 1056659
Data columns (total 19 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   cord_uid          1056660 non-null  object
 1   sha               373766 non-null   object
 2   source_x          1056660 non-null  object
 3   title             1056157 non-null  object
 4   doi               656780 non-null   object
 5   pmcid             389571 non-null   object
 6   pubmed_id         498932 non-null   object
 7   license           1056660 non-null  object
 8   abstract          821116 non-null   object
 9   publish_time      1054846 non-null  object
 10  authors           1032791 non-null  object
 11  journal           969338 non-null   object
 12  mag_id            0 non-null        float64
 13  who_covidence_id  482935 non-null   object
 14  arxiv_id          14249 non-null    object
 15  pdf_json_files    373766 non-null   object
 16  pmc_json_files    315742 non-null   object
 17  url               686934 non-null   object
 18  s2_id             976468 non-null   float64
dtypes: float64(2), object(17)
memory usage: 153.2+ MB

In [ ]:
sample_size = 10000
random_seed = 42
json_path = 'metadata_sample.json'
df_sample = df.sample(n=sample_size, random_state=random_seed)

In [13]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 17948 to 810205
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          10000 non-null  object
 1   sha               3543 non-null   object
 2   source_x          10000 non-null  object
 3   title             9998 non-null   object
 4   doi               6297 non-null   object
 5   pmcid             3691 non-null   object
 6   pubmed_id         4695 non-null   object
 7   license           10000 non-null  object
 8   abstract          7779 non-null   object
 9   publish_time      9984 non-null   object
 10  authors           9790 non-null   object
 11  journal           9120 non-null   object
 12  mag_id            0 non-null      float64
 13  who_covidence_id  4492 non-null   object
 14  arxiv_id          142 non-null    object
 15  pdf_json_files    3543 non-null   object
 16  pmc_json_files    2999 non-null   object
 17  url               6571 non-null   object
 18  s2_id             9229 non-null   float64
dtypes: float64(2), object(17)
memory usage: 1.5+ MB

In [19]:
df_sample_filtered = df_sample.dropna(axis=1, how="all").dropna(axis=0, subset=['title', 'abstract', 'publish_time', 'authors'])

df_sample_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7735 entries, 17948 to 159411
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cord_uid          7735 non-null   object
 1   sha               3072 non-null   object
 2   source_x          7735 non-null   object
 3   title             7735 non-null   object
 4   doi               5079 non-null   object
 5   pmcid             2925 non-null   object
 6   pubmed_id         3755 non-null   object
 7   license           7735 non-null   object
 8   abstract          7735 non-null   object
 9   publish_time      7735 non-null   object
 10  authors           7735 non-null   object
 11  journal           6939 non-null   object
 12  who_covidence_id  3336 non-null   object
 13  arxiv_id          142 non-null    object
 14  pdf_json_files    3072 non-null   object
 15  pmc_json_files    2547 non-null   object
 16  url               5312 non-null   object
 17  s2_id             7206 non-null   float64
dtypes: float64(1), object(17)
memory usage: 1.1+ MB

In [20]:
df_sample_filtered.head()

,cord_uid,sha,source_x,title,doi,pmcid,pubmed_id,license,abstract,publish_time,authors,journal,who_covidence_id,arxiv_id,pdf_json_files,pmc_json_files,url,s2_id
17948,ak20jg32,42a61efa32fae8fb14d1c8c1a8bc528c59e1583a,PMC,Development and Internal Validation of a Novel...,10.3389/fpsyt.2021.593710,PMC8172985,34093252,cc-by,Objective: The aim of our study was to identif...,2021-05-20,"Zhou, Jingjing; Zhou, Jia; Sun, Zuoli; Feng, L...",Front Psychiatry,NaN,NaN,document_parses/pdf_json/42a61efa32fae8fb14d1c...,document_parses/pmc_json/PMC8172985.xml.json,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8...,NaN
922293,6unac0pg,36ada922d634878a962c1f555ad144969c168e08,BioRxiv; WHO,Single domain shark VNAR antibodies neutralize...,10.1101/2021.06.08.447530,NaN,NaN,biorxiv,Single domain shark VNAR antibodies can offer ...,2021-06-08,"Gauhar, Aziz; Privezentzev, Cyril V; Demydchuk...",bioRxiv,NaN,NaN,document_parses/pdf_json/36ada922d634878a962c1...,NaN,https://doi.org/10.1101/2021.06.08.447530,235396724.0
455876,fcc1cohr,NaN,WHO,Point-of-care ultrasound during the COVID-19 p...,NaN,NaN,NaN,unk,PURPOSE: The coronavirus disease-2019 (COVID-1...,2021,"Yuriditsky, Eugene; Saric, Muhamed; Horowitz, ...",Echocardiography,#1084702,NaN,NaN,NaN,NaN,231925832.0
775710,73xyjolv,86bb8af8dfc34b7a8e6ff25b0167a1bda02fa0e9,PMC; WHO,Joint Predictive Value of cTnI and NT-proBNP o...,10.2478/jtim-2021-0034,PMC8629414,NaN,cc-by-nc-nd,BACKGROUND AND OBJECTIVES: The pandemic of cor...,2021-09-28,"Weng, Haoyu; Yang, Fan; Zhang, Long; Jin, Han;...",J Transl Int Med,NaN,NaN,document_parses/pdf_json/86bb8af8dfc34b7a8e6ff...,document_parses/pmc_json/PMC8629414.xml.json,https://doi.org/10.2478/jtim-2021-0034,238220710.0
115080,k82ifpki,NaN,Medline,Glass hybrid (glass ionomer) versus composite ...,10.1016/j.jdent.2021.103689,NaN,33979577,unk,"OBJECTIVE This study compared survival, restor...",2021-05-09,"Schwendicke, Falk; Müller, Anne; Seifert, Tilm...",Journal of dentistry,NaN,NaN,NaN,NaN,https://doi.org/10.1016/j.jdent.2021.103689; h...,234485613.0

In [21]:
df_sample_filtered.to_json(json_path, orient='records', indent=2)